
random article from a category alphabeticle

http://en.wikipedia.org/w/api.php?action=query&list=random&generator=categorymembers&gcmtitle=Category:American%20websites&prop=info&prop=extrac
ts&exintro=&explaintext&exlimit=max&continue


Category of an acrticle
https://en.wikipedia.org/w/api.php?format=xml&action=query&prop=categories&titles=cricket

Continue 
http://en.wikipedia.org/w/api.php?action=query&list=random&generator=categorymembers&gcmtitle=Category:Team%20sports&prop=info&prop=extracts&exintro=&explaintext&exlimit=max&continue=gcmcontinue||random&rnlimit=10&rnnamespace=0&gcmcontinue=page|43414d4d4147|6299431

